# Netlify Configuration for TimeFlow Pro
[build]
  # Build command
  command = "npm run build"
  
  # Directory to deploy (contains built files)
  publish = "dist"
  
  # Node version for build process
  environment = { NODE_VERSION = "18" }

# Build settings
[build.environment]
  NPM_FLAGS = "--no-optional"

# Redirect rules for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Security headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://api.asana.com https://api.jsonbin.io; img-src 'self' data: https:;"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache CSS and JS files
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# PWA configuration
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/manifest+json"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Forms processing (if needed for feedback)
[functions]
  directory = "functions"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 3000
  
# Branch deploy previews
[context.deploy-preview]
  command = "npm run build:preview"
  
[context.branch-deploy]
  command = "npm run build:staging"