# Cloudflare Pages Configuration for TimeFlow Pro
name = "timeflow-pro"
compatibility_date = "2024-01-01"

[env.production]
# Production environment settings
vars = { ENVIRONMENT = "production" }

[env.preview]
# Preview/staging environment
vars = { ENVIRONMENT = "preview" }

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Pages configuration  
[pages]
# Build output directory
build_output_dir = "dist"
# Build command
build_command = "npm run build"

# Custom headers and redirects
[[pages.rules]]
pattern = "/*"
headers = { "X-Frame-Options" = "DENY", "X-Content-Type-Options" = "nosniff" }

# Cache static assets
[[pages.rules]]
pattern = "/assets/*"
headers = { "Cache-Control" = "public, max-age=31536000, immutable" }

# SPA routing - redirect all routes to index.html
[[pages.redirects]]
from = "/*"
to = "/index.html"
status = 200